services:
  - type: web
    name: ai-project-maker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh 
    envVars:
      - key: API_KEY_1 
        sync: false
      - key: BASE_URL
        value: https://ai.bluepack.my.id/anthropic
      - key: MODEL_1
        value: claude-sonnet-4-5
